### PR TITLE
Update WASM card

### PR DESCRIPTION
**Pull request by killercup**
Not really finished, I still want to replace the two book chapter links

### CODE REVIEW

**Comment by killercup** [comment]
This already includes a bunch of feedback from @mgattozzi.

r? @fitzgen -- who I warned that a ping about this would be coming

**Review by fitzgen — APPROVED** [review]
This is super awesome! I don't really have much to add because it is in a great spot already!

Nitpicks:

* the bottom left section, listing wasm-bindgen, etc: it isn't clear at a glance whether the description is for the thing above or below the description, and a little whitespace padding could do wonders IMO.

* https://webassembly.org/ uses "Wasm" instead of "WASM", and I tend to follow that convention

* I don't know if there is room, but maybe give an overview of what is in the book? Something like "tutorial, debugging, time profiling, size profiling"? Also, the links to the crates and tools pages will go from "/book/whatever.html" to "/book/reference/whatever.html" soonish. It might be better to just link the book and then have bullet points for its different contents?

**Comment by killercup** [comment]
@fitzgen thanks! Updated with your feedback. I'm gonna print this in half an hour – anyone want to have some last minute changes? (cc @mgattozzi)

**Comment by badboy** [comment]
This is in print right now, so merging.

**Pull request merged**
